import { FeeDetailOrigin } from "../../common/DTO/fee-detail-origin";

// Descriptor del breadcrumb cuando Fee Updates navega a Fee Detail (self-describing).
export const FEE_UPDATES_BREADCRUMB: FeeDetailOrigin = { labelKey: "LBL_FEE_UPDATES", path: "/fee/updates" };

export const FEE_UPDATES_CONSTANTS = {
	DEFAULT_PAGE_SIZE: 10,
	MAX_DATE_RANGE_MONTHS: 12,
	SEARCH_FIELDS: ["feeCode", "feeName", "category"] as const,
	EMPTY_VALUE_PLACEHOLDER: "-",
	EXPORT_SHEET_FILTERS: "Filters Applied",
	ABSOLUTE_CHANGE_TOOLTIP_KEY: "LBL_ABSOLUTE_CHANGE_TOOLTIP",
} as const;

export const FEE_UPDATES_TERM = {
	TITLE: "LBL_FEE_UPDATES",

	TAB_NEW_FEES: "LBL_NEW_FEES",
	TAB_TARIFF_CHANGES: "LBL_TARIFF_CHANGES",
	TAB_CEASED_FEES: "LBL_CEASED_FEES",

	CARD_NEW_FEES: "LBL_NEW_FEES",
	CARD_TARIFF_CHANGES: "LBL_TARIFF_CHANGES",
	CARD_CEASED_FEES: "LBL_CEASED_FEES",

	FLT_ALL_INSTITUTIONS: "ALL_INSTITUTIONS",
	FLT_DATE_RANGE: "LBL_DATE_RANGE",
	FLT_ALL_BRANDS: "LBL_ALL_BRANDS",
	FLT_ALL_BUSINESSES: "LBL_ALL_BUSINESSES",
	FLT_ENTITIES: "Entities",
	FLT_BRANDS: "Brands",
	FLT_BUSINESSES: "Businesses",
	INSTITUTIONS_SELECTED: "INSTITUTIONS_SELECTED",
	BRANDS_SELECTED: "LBL_BRAND_SELECTED",
	BUSINESSES_SELECTED: "LBL_BUSINESS_SELECTED",
	REQUIRED_FILTER: "LBL_REQUIRED_FILTER",
	SELECT_AT_LEAST_ONE_BEFORE_APPLYING: "LBL_SELECT_AT_LEAST_ONE_BEFORE_APPLYING",
	FLT_APPLY: "Apply",
	FLT_RESET: "LBL_RESET",
	FLT_ADVANCED: "LBL_ADVANCED",
	FLT_LAST_12_MONTHS: "LBL_LAST_12_MONTHS",
	FLT_CURRENT_YEAR: "LBL_CURRENT_YEAR",
	FLT_CURRENT_MONTH: "LBL_CURRENT_MONTH",

	COL_FEE_CODE: "LBL_FEE_CODE",
	COL_FEE_NAME: "LBL_FEE_NAME",
	COL_INSTITUTION: "INSTITUTION",
	COL_CATEGORY: "LBL_CATEGORY",
	COL_BRAND: "LBL_BRAND",
	COL_BUSINESS: "LBL_BUSINESS",
	COL_FIRST_BILLING_DATE: "LBL_FIRST_BILLING_DATE",
	COL_AMOUNT_IN: "LBL_AMOUNT_IN",
	COL_PREVIOUS_RATE: "LBL_PREVIOUS_RATE",
	COL_NEW_RATE: "LBL_NEW_RATE",
	COL_ABSOLUTE_CHANGE_IN: "LBL_ABSOLUTE_CHANGE_IN",
	COL_ABSOLUTE_CHANGE: "LBL_ABSOLUTE_CHANGE",
	COL_CHANGE_DATE: "LBL_CHANGE_DATE",
	COL_LAST_KNOWN_RATE: "LBL_LAST_KNOWN_RATE",
	COL_CEASED_DATE: "LBL_CEASED_DATE",
	COL_CURRENCY: "LBL_CURRENCY",
	COL_TOTAL: "LBL_TOTAL",

	DESC_NEW_FEES: "LBL_DESC_NEW_FEES",
	DESC_TARIFF_CHANGES: "LBL_DESC_TARIFF_CHANGES",
	DESC_CEASED_FEES: "LBL_DESC_CEASED_FEES",

	SEARCH_PLACEHOLDER: "LBL_SEARCH_TEXT_HERE",
	NO_DATA_TO_EXPORT: "SM_NO_DATA_TO_EXPORT",

	EXPORT_TOOLTIP: "LBL_EXPORT_EXCEL",
	EXPORT_NAME: "LBL_NAME_FEE_UPDATES_EXPORT",

	LBL_PREPARING_FILE: "LBL_PREPARING_FILE",
	LBL_DOWNLOAD_START_FILE: "LBL_DOWNLOAD_START_FILE",
	LBL_FILE_DOWNLOAD_SUCCESS: "LBL_FILE_DOWNLOAD_SUCCESS",
	LBL_FILE_DOWNLOAD_DEVICE: "LBL_FILE_DOWNLOAD_DEVICE",
	LBL_FILE_FAILED_DOWNLOAD: "LBL_FILE_FAILED_DOWNLOAD",
	LBL_FILE_CONTACT_SUPPORT: "LBL_FILE_CONTACT_SUPPORT",

	STATE_NO_DATA_TITLE: "LBL_NO_DATA_TITLE",
	STATE_NO_DATA_BODY: "LBL_NO_DATA_BODY",
	STATE_NO_MATCHES_TITLE: "LBL_NO_MATCHES_TITLE",
	STATE_NO_MATCHES_BODY: "LBL_NO_MATCHES_BODY",
	STATE_SYSTEM_ERROR_TITLE: "LBL_SYSTEM_ERROR_TITLE",
	STATE_SYSTEM_ERROR_BODY: "LBL_SYSTEM_ERROR_BODY",
	STATE_RELOAD_PAGE: "LBL_RELOAD_PAGE",

	ABSOLUTE_CHANGE_TOOLTIP: "LBL_ABSOLUTE_CHANGE_TOOLTIP",
} as const;
