export const COMMON_TERM = {
	LBL_LAST_12: "LBL_LAST_12_MONTHS",
	LBL_CURRENT_YEAR: "LBL_CURRENT_YEAR",
	LBL_CURRENT_MONTH: "LBL_CURRENT_MONTH",
	BTN_APPLY: "BTN_APPLY",
	BTN_RESET: "LBL_RESET",
	BTN_CLEAR: "BTN_CLEAR",
	BTN_CLOSE: "BTN_CLOSE",
	BTN_DOWNLOAD: "BTN_DOWNLOAD",
	NODATA: "Nodata",
} as const;
